### ISSUE TITLE
Feature Request: Narration Box

### ISSUE THREAD

**Issue by isakgrozny** [affinity-engine/affinity-engine#2]
One thing I think would be a very useful plugin is a narration box that goes outside the backdrop, where non-dialogue text could go. What do you think?

**Comment by null-null-null** [comment]
You might already be able to do with the `script.text` direction. That is,
you can have multiple `text` directions on the screen at once. It would
just be a matter of styling one of them to be your narration box:

```
const dialogue = script.text('Hello!');
const narration = script.text('The Throne Room of King Evil').classNames({
structural: ['narration-box'] });
```

You would need to define a `narration-box` class in your css, too:

```
// app.scss
.narration-box {
  position: absolute;
  top: 5px;
}
```

The only problem is that the narration box will close on keypress or click
events. I could rig it up to be manual though.

**Comment by isakgrozny** [comment]
That'd be ideal, thank you!

**Comment by null-null-null** [comment]
Hey @isakgrozny! Sorry for the long silence on this issue. I was overhauling a lot of the deep internals for the Affinity Engine, and I believe the end result is a significantly improved ecosystem of addons. (And a better api for making custom directions.) Anyway, now that that's done, I've added support for this. The api looks like this:

```js
import { Scene } from 'affinity-engine-stage';
import { task } from 'ember-concurrency';

export default Scene.extend({
  name: 'Text Direction Test',

  start: task(function * (script) {
    const staticText = script.text('Click me and I will stay').static();

    yield script.text('Click me and I will disappear');

    staticText.close(); // closes the static text
  })
});
```

You'll also notice that scripts have moved away from using `await` and towards using `ember-concurrency` and `yield`. To update from the old syntax, you can simply replace `await` with `yield` and `start: async function(script) {` with `start: task(function * (script) {`. You'll also need to close `start` with a `})` instead of just a `}`. And you'll need to add `import { task } from 'ember-concurrency';` to the top of the file.
